version: 2

sources:
  - name: sales_store
    description: This schema tells about all of the info realted to sales
    database: BikeStores
    schema: sales
    tables:
      - name: customers


  - name: production_store
    description: This schema tells about all of the info realted to prodution database
    database: BikeStores
    schema: production
    tables:
      - name: categories


